### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tobeycodes**

### CODE REVIEW

**Comment by tobeycodes** [comment]
@blurrah What are your thoughts on this change? We were unable to get this working without setting up like this change.

**Comment by blurrah** [comment]
Hey @tobeycodes good call! With the 3.0 update it should no longer return a rewrite header since we produce a response. So I think it should check for the `WWW-Authenticate` header instead.
```js
if (basicAuth.headers.has('WWW-Authenticate')) {
  return basicAuth
}
```

I can see if I can add a test or example case for it, can you double check it in the meantime and update the PR if possible? 
This should also work for v2 as well so no need to have separate docs around this

**Comment by tobeycodes** [comment]
@blurrah I'll take a look at 3.0 and see. Congrats on the release.

Should the basic auth actually work without returning it? I'm still unsure if this is the README being incorrect when using `nextBasicAuthMiddleware` in a larger middleware function or if I am using the package incorrectly. As I mentioned the only way I could get this working in a larger middleware function was to return it.

**Comment by blurrah** [comment]
Thanks! To be honest I've been way too focused on the all-in approach and should have a working example running for using it in a larger middleware function. That's why I might have missed this part of the implementation, my bad! 

Will see if I can get that example in somewhere this/next week and should set up some playwright tests for both examples.

**Pull request closed without merging**
